# Generated by Django 3.2.7 on 2022-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRegisterComplaintModel',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('status_category', models.CharField(default='pending', max_length=100, null=True)),
                ('status_category_2', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'citizen_complaints',
            },
        ),
        migrations.CreateModel(
            name='CitizenRegisterModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'citizen_details',
            },
        ),
    ]
